# Generated by Django 3.2 on 2022-05-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='account',
        ),
    ]
